{
    'name': 'Parking Management',
    'version': '15.0.0.0',
    'summary': 'Manage the parking of vehicles',
    'sequence': -10,
    'description': """This module is developed for managing the vehicle 
    parking and providing the parking tickets for any type of customers.""",
    'category': 'Industries',
    'author': 'Techno Solutions',
    'company': 'Techno Solutions',
    'maintainer': ' Techno Solutions',
    'website': 'https://www.techsolu.com',
    'depends': ['base', 'fleet', 'account'],
    'data': [
        'security/odoo_parking_management_groups.xml',
        'security/parking_entry_security.xml',
        'security/ir.model.access.csv',
        'data/report_paperformat_data.xml',
        'data/data_sequence.xml',
        'report/parking_ticket_report_templates.xml',
        'wizard/register_payment_views.xml',
        'views/parking_entry_views.xml',
        'views/slot_type_views.xml',
        'views/location_details_views.xml',
        'views/slot_details_views.xml',
        'views/member_slot_reservation_views.xml',
        'views/vehicle_details_views.xml',
        'views/menu.xml',
    ],
    'images': ['static/description/banner.png'],
    'installable': True,
    'application': True,
    'auto_install': False,
}
